package queue

import (
	"context"
	"fmt"
	"log/slog"
	"os"
	"path/filepath"
	"text/template"

	"github.com/vici2/dialer/internal/esl"
)

// IngroupRenderer renders FreeSWITCH dialplan XML for in-groups.
// I01 PLAN §15.
type IngroupRenderer struct {
	dialplanDir string
	tmpl        *template.Template
	eslCli      *esl.Client
	fsHost      string
	log         *slog.Logger
}

// NewIngroupRenderer creates an IngroupRenderer.
// dialplanDir is the path to freeswitch/conf/dialplan/default/ on the shared volume.
func NewIngroupRenderer(dialplanDir string, eslCli *esl.Client, fsHost string, log *slog.Logger) (*IngroupRenderer, error) {
	if log == nil {
		log = slog.Default()
	}

	tmpl, err := template.New("ingroup.xml").Parse(ingroupXMLTemplate)
	if err != nil {
		return nil, fmt.Errorf("ingroupRenderer: parse template: %w", err)
	}

	return &IngroupRenderer{
		dialplanDir: dialplanDir,
		tmpl:        tmpl,
		eslCli:      eslCli,
		fsHost:      fsHost,
		log:         log,
	}, nil
}

// ingroupXMLTemplate is the FreeSWITCH dialplan template for one in-group.
// I01 PLAN §7.2 + §15.1 (FROZEN extension naming: ingroup_{id}).
const ingroupXMLTemplate = `<?xml version="1.0" encoding="UTF-8"?>
<!--
  Auto-generated by I01 IngroupRenderer — DO NOT EDIT.
  In-group: {{.ID}} | Tenant: {{.TenantID}}
  I01 PLAN §15.1: extension name = ingroup_{{.ID}}
-->
<include>
  <extension name="ingroup_{{.ID}}">
    <condition field="destination_number" expression="^ingroup_{{.ID}}$">
      <action application="set"      data="vici2_role=customer_leg"/>
      <action application="set"      data="vici2_ingroup_id={{.ID}}"/>
      <action application="set"      data="vici2_tenant_id={{.TenantID}}"/>
      <action application="set"      data="hangup_after_bridge=false"/>
      <action application="set"      data="continue_on_fail=true"/>
      <action application="set"      data="vici2_recording_mode={{.RecordingMode}}"/>
      <action application="answer"/>
      {{- if .WelcomeAudio}}
      <!-- One-shot welcome audio (I01 PLAN §7.1) -->
      <action application="playback" data="{{.WelcomeAudio}}"/>
      {{- end}}
      <!-- MOH for park -->
      <action application="set"      data="hold_music={{.MOHStream}}"/>
      <!-- Enroll in Redis queue via API (I01 PLAN §7.2) -->
      <action application="curl"     data="${api_url}/internal/queue/enroll?call_uuid=${uuid}&amp;ingroup={{.ID}}&amp;tenant={{.TenantID}} post"/>
      <!-- Park: dispatcher will uuid_transfer to agent conf when ready -->
      <action application="park"/>
      <!-- Reached only on park failure / dispatcher timeout -->
      <action application="curl"     data="${api_url}/internal/queue/timeout?call_uuid=${uuid} post"/>
      <action application="hangup"   data="NORMAL_CLEARING"/>
    </condition>
  </extension>
</include>
`

// ingroupTemplateData is passed to the XML template.
type ingroupTemplateData struct {
	ID            string
	TenantID      int64
	RecordingMode RecordingMode
	MOHStream     string
	WelcomeAudio  string
}

// Render generates the dialplan XML for the given in-group and writes it to disk.
// Then issues bgapi reloadxml. I01 PLAN §15.2.
func (r *IngroupRenderer) Render(ctx context.Context, ig *InGroup) error {
	data := ingroupTemplateData{
		ID:            ig.ID,
		TenantID:      ig.TenantID,
		RecordingMode: ig.RecordingMode,
		MOHStream:     ig.MOHStream,
	}
	if ig.WelcomeAudio != nil {
		data.WelcomeAudio = *ig.WelcomeAudio
	}
	if data.MOHStream == "" {
		data.MOHStream = "local_stream://moh"
	}

	filename := filepath.Join(r.dialplanDir, fmt.Sprintf("60_ingroup_%s.xml", ig.ID))

	f, err := os.Create(filename)
	if err != nil {
		return fmt.Errorf("ingroupRenderer: create %s: %w", filename, err)
	}
	defer f.Close()

	if err := r.tmpl.Execute(f, data); err != nil {
		return fmt.Errorf("ingroupRenderer: execute template for %s: %w", ig.ID, err)
	}

	r.log.Info("ingroupRenderer: rendered XML", "ingroup", ig.ID, "file", filename)

	// bgapi reloadxml — idempotent, zero downtime.
	// I01 PLAN §15.2.
	if r.eslCli != nil {
		if err := r.eslCli.Reload(ctx, r.fsHost, "xml"); err != nil {
			r.log.Warn("ingroupRenderer: reloadxml failed", "err", err)
			// Non-fatal: FS will pick up on next restart.
		}
	}

	return nil
}

// Delete removes the dialplan XML for a deleted in-group.
// I01 PLAN §15.2.
func (r *IngroupRenderer) Delete(ctx context.Context, ingroupID string) error {
	filename := filepath.Join(r.dialplanDir, fmt.Sprintf("60_ingroup_%s.xml", ingroupID))
	if err := os.Remove(filename); err != nil && !os.IsNotExist(err) {
		return fmt.Errorf("ingroupRenderer: remove %s: %w", filename, err)
	}

	if r.eslCli != nil {
		if err := r.eslCli.Reload(ctx, r.fsHost, "xml"); err != nil {
			r.log.Warn("ingroupRenderer: reloadxml after delete", "err", err)
		}
	}

	return nil
}
