// Code generated by tcpa-rulesgen from db/seeds/state_rules.csv; DO NOT EDIT.
// Source: db/seeds/state_rules.csv
// Federal floor (fed_8_21) is always applied first; entries here are
// ADDITIONAL restrictions that narrow or replace the federal window.

package tcpa

import "time"

// stateRules maps 2-letter US state codes to their calling restrictions.
// Any state not listed defaults to the federal floor (08:00–21:00, all days).
// Generated: 2026-05-13
var stateRules = map[string]StateRule{
	"AL": {
		Code: "AL",
		PerDow: [7]Window{
			0: {OpenLocal: 25 * time.Hour, CloseLocal: 0}, // Sun: blackout (open > close = no calls)
			1: {OpenLocal: 8 * time.Hour, CloseLocal: 20 * time.Hour},
			2: {OpenLocal: 8 * time.Hour, CloseLocal: 20 * time.Hour},
			3: {OpenLocal: 8 * time.Hour, CloseLocal: 20 * time.Hour},
			4: {OpenLocal: 8 * time.Hour, CloseLocal: 20 * time.Hour},
			5: {OpenLocal: 8 * time.Hour, CloseLocal: 20 * time.Hour},
			6: {OpenLocal: 8 * time.Hour, CloseLocal: 20 * time.Hour},
		},
		HolidayBlackout: []HolidayMatcher{
			{Kind: "fixed", Value: "2026-01-01"}, // New Year's Day
			{Kind: "fixed", Value: "2026-12-25"}, // Christmas Day
		},
		Comment: "Ala. Admin. Code 770-X-5-.17",
	},
	"CT": {
		Code: "CT",
		PerDow: [7]Window{
			0: {OpenLocal: 9 * time.Hour, CloseLocal: 20 * time.Hour},
			1: {OpenLocal: 9 * time.Hour, CloseLocal: 20 * time.Hour},
			2: {OpenLocal: 9 * time.Hour, CloseLocal: 20 * time.Hour},
			3: {OpenLocal: 9 * time.Hour, CloseLocal: 20 * time.Hour},
			4: {OpenLocal: 9 * time.Hour, CloseLocal: 20 * time.Hour},
			5: {OpenLocal: 9 * time.Hour, CloseLocal: 20 * time.Hour},
			6: {OpenLocal: 9 * time.Hour, CloseLocal: 20 * time.Hour},
		},
		Comment: "Conn. Gen. Stat. 42-288a(c); 9am start + 8pm cutoff",
	},
	"FL": {
		Code: "FL",
		PerDow: [7]Window{
			0: {OpenLocal: 8 * time.Hour, CloseLocal: 20 * time.Hour},
			1: {OpenLocal: 8 * time.Hour, CloseLocal: 20 * time.Hour},
			2: {OpenLocal: 8 * time.Hour, CloseLocal: 20 * time.Hour},
			3: {OpenLocal: 8 * time.Hour, CloseLocal: 20 * time.Hour},
			4: {OpenLocal: 8 * time.Hour, CloseLocal: 20 * time.Hour},
			5: {OpenLocal: 8 * time.Hour, CloseLocal: 20 * time.Hour},
			6: {OpenLocal: 8 * time.Hour, CloseLocal: 20 * time.Hour},
		},
		Comment: "Fla. Stat. 501.616 (FTSA); 8pm cutoff",
	},
	"KY": {
		Code: "KY",
		PerDow: [7]Window{
			0: {OpenLocal: 10 * time.Hour, CloseLocal: 21 * time.Hour},
			1: {OpenLocal: 10 * time.Hour, CloseLocal: 21 * time.Hour},
			2: {OpenLocal: 10 * time.Hour, CloseLocal: 21 * time.Hour},
			3: {OpenLocal: 10 * time.Hour, CloseLocal: 21 * time.Hour},
			4: {OpenLocal: 10 * time.Hour, CloseLocal: 21 * time.Hour},
			5: {OpenLocal: 10 * time.Hour, CloseLocal: 21 * time.Hour},
			6: {OpenLocal: 10 * time.Hour, CloseLocal: 21 * time.Hour},
		},
		Comment: "KRS 367.46955; latest start (10am) in nation",
	},
	"LA": {
		Code: "LA",
		PerDow: [7]Window{
			0: {OpenLocal: 25 * time.Hour, CloseLocal: 0}, // blackout sentinel: open > close
			1: {OpenLocal: 8 * time.Hour, CloseLocal: 20 * time.Hour},
			2: {OpenLocal: 8 * time.Hour, CloseLocal: 20 * time.Hour},
			3: {OpenLocal: 8 * time.Hour, CloseLocal: 20 * time.Hour},
			4: {OpenLocal: 8 * time.Hour, CloseLocal: 20 * time.Hour},
			5: {OpenLocal: 8 * time.Hour, CloseLocal: 20 * time.Hour},
			6: {OpenLocal: 8 * time.Hour, CloseLocal: 20 * time.Hour},
		},
		HolidayBlackout: []HolidayMatcher{
			{Kind: "named", Value: "MARDI_GRAS"},
			{Kind: "easter_offset", Value: "-2"}, // Good Friday
		},
		Comment: "La. R.S. 45:844.31; 8pm cutoff M-Sat; Sunday blackout; Mardi Gras + Good Friday blackout",
	},
	"MD": {
		Code: "MD",
		PerDow: [7]Window{
			0: {OpenLocal: 8 * time.Hour, CloseLocal: 20 * time.Hour},
			1: {OpenLocal: 8 * time.Hour, CloseLocal: 20 * time.Hour},
			2: {OpenLocal: 8 * time.Hour, CloseLocal: 20 * time.Hour},
			3: {OpenLocal: 8 * time.Hour, CloseLocal: 20 * time.Hour},
			4: {OpenLocal: 8 * time.Hour, CloseLocal: 20 * time.Hour},
			5: {OpenLocal: 8 * time.Hour, CloseLocal: 20 * time.Hour},
			6: {OpenLocal: 8 * time.Hour, CloseLocal: 20 * time.Hour},
		},
		Comment: "Md. Com. Law 14-3201 (Stop the Spam Calls Act); 8pm cutoff",
	},
	"MA": {
		Code: "MA",
		PerDow: [7]Window{
			0: {OpenLocal: 8 * time.Hour, CloseLocal: 20 * time.Hour},
			1: {OpenLocal: 8 * time.Hour, CloseLocal: 20 * time.Hour},
			2: {OpenLocal: 8 * time.Hour, CloseLocal: 20 * time.Hour},
			3: {OpenLocal: 8 * time.Hour, CloseLocal: 20 * time.Hour},
			4: {OpenLocal: 8 * time.Hour, CloseLocal: 20 * time.Hour},
			5: {OpenLocal: 8 * time.Hour, CloseLocal: 20 * time.Hour},
			6: {OpenLocal: 8 * time.Hour, CloseLocal: 20 * time.Hour},
		},
		Comment: "MGL Ch.159C 3; 8pm cutoff",
	},
	"ME": {
		Code: "ME",
		PerDow: [7]Window{
			// Sun: live calls follow fed; autodialer blackout (see AutoDialerBlackoutDows)
			0: {OpenLocal: 8 * time.Hour, CloseLocal: 21 * time.Hour},
			// Mon-Fri: live calls follow fed; autodialer 09:00-17:00
			1: {OpenLocal: 8 * time.Hour, CloseLocal: 21 * time.Hour},
			2: {OpenLocal: 8 * time.Hour, CloseLocal: 21 * time.Hour},
			3: {OpenLocal: 8 * time.Hour, CloseLocal: 21 * time.Hour},
			4: {OpenLocal: 8 * time.Hour, CloseLocal: 21 * time.Hour},
			5: {OpenLocal: 8 * time.Hour, CloseLocal: 21 * time.Hour},
			// Sat: live calls follow fed; autodialer blackout (see AutoDialerBlackoutDows)
			6: {OpenLocal: 8 * time.Hour, CloseLocal: 21 * time.Hour},
		},
		// AutoDialerOnly: Mon-Fri 09:00-17:00 for autodialers.
		AutoDialerOnly: &Window{OpenLocal: 9 * time.Hour, CloseLocal: 17 * time.Hour},
		// AutoDialerBlackoutDows: bit 0 (Sun) + bit 6 (Sat) = 0b1000001 = 0x41
		AutoDialerBlackoutDows: 0x41, // Sun=bit0, Sat=bit6
		Comment:                "10 M.R.S. 1498; autodialer: M-F 9-5 only; Sat/Sun blackout",
	},
	"MI": {
		Code: "MI",
		PerDow: [7]Window{
			0: {OpenLocal: 9 * time.Hour, CloseLocal: 21 * time.Hour},
			1: {OpenLocal: 9 * time.Hour, CloseLocal: 21 * time.Hour},
			2: {OpenLocal: 9 * time.Hour, CloseLocal: 21 * time.Hour},
			3: {OpenLocal: 9 * time.Hour, CloseLocal: 21 * time.Hour},
			4: {OpenLocal: 9 * time.Hour, CloseLocal: 21 * time.Hour},
			5: {OpenLocal: 9 * time.Hour, CloseLocal: 21 * time.Hour},
			6: {OpenLocal: 9 * time.Hour, CloseLocal: 21 * time.Hour},
		},
		Comment: "MCL 750.540e(f); 9am start",
	},
	"MN": {
		Code: "MN",
		PerDow: [7]Window{
			0: {OpenLocal: 9 * time.Hour, CloseLocal: 21 * time.Hour},
			1: {OpenLocal: 9 * time.Hour, CloseLocal: 21 * time.Hour},
			2: {OpenLocal: 9 * time.Hour, CloseLocal: 21 * time.Hour},
			3: {OpenLocal: 9 * time.Hour, CloseLocal: 21 * time.Hour},
			4: {OpenLocal: 9 * time.Hour, CloseLocal: 21 * time.Hour},
			5: {OpenLocal: 9 * time.Hour, CloseLocal: 21 * time.Hour},
			6: {OpenLocal: 9 * time.Hour, CloseLocal: 21 * time.Hour},
		},
		Comment: "Minn. Stat. 325E.30; 9am start",
	},
	"MS": {
		Code: "MS",
		PerDow: [7]Window{
			0: {OpenLocal: 25 * time.Hour, CloseLocal: 0}, // blackout
			1: {OpenLocal: 8 * time.Hour, CloseLocal: 20 * time.Hour},
			2: {OpenLocal: 8 * time.Hour, CloseLocal: 20 * time.Hour},
			3: {OpenLocal: 8 * time.Hour, CloseLocal: 20 * time.Hour},
			4: {OpenLocal: 8 * time.Hour, CloseLocal: 20 * time.Hour},
			5: {OpenLocal: 8 * time.Hour, CloseLocal: 20 * time.Hour},
			6: {OpenLocal: 8 * time.Hour, CloseLocal: 20 * time.Hour},
		},
		Comment: "Miss. Code Ann. 77-3-723; 8pm cutoff M-Sat; Sunday blackout",
	},
	"OK": {
		Code: "OK",
		PerDow: [7]Window{
			0: {OpenLocal: 8 * time.Hour, CloseLocal: 20 * time.Hour},
			1: {OpenLocal: 8 * time.Hour, CloseLocal: 20 * time.Hour},
			2: {OpenLocal: 8 * time.Hour, CloseLocal: 20 * time.Hour},
			3: {OpenLocal: 8 * time.Hour, CloseLocal: 20 * time.Hour},
			4: {OpenLocal: 8 * time.Hour, CloseLocal: 20 * time.Hour},
			5: {OpenLocal: 8 * time.Hour, CloseLocal: 20 * time.Hour},
			6: {OpenLocal: 8 * time.Hour, CloseLocal: 20 * time.Hour},
		},
		Comment: "15 OS 775C.4 (OTSA); 8pm cutoff",
	},
	"PA": {
		Code: "PA",
		PerDow: [7]Window{
			0: {OpenLocal: 12 * time.Hour, CloseLocal: 21 * time.Hour}, // Sun noon start
			1: {OpenLocal: 8 * time.Hour, CloseLocal: 21 * time.Hour},
			2: {OpenLocal: 8 * time.Hour, CloseLocal: 21 * time.Hour},
			3: {OpenLocal: 8 * time.Hour, CloseLocal: 21 * time.Hour},
			4: {OpenLocal: 8 * time.Hour, CloseLocal: 21 * time.Hour},
			5: {OpenLocal: 8 * time.Hour, CloseLocal: 21 * time.Hour},
			6: {OpenLocal: 8 * time.Hour, CloseLocal: 21 * time.Hour},
		},
		Comment: "73 P.S. 2245.4; Sunday noon start",
	},
	"RI": {
		Code: "RI",
		PerDow: [7]Window{
			0: {OpenLocal: 25 * time.Hour, CloseLocal: 0}, // Sunday blackout
			1: {OpenLocal: 9 * time.Hour, CloseLocal: 18 * time.Hour},
			2: {OpenLocal: 9 * time.Hour, CloseLocal: 18 * time.Hour},
			3: {OpenLocal: 9 * time.Hour, CloseLocal: 18 * time.Hour},
			4: {OpenLocal: 9 * time.Hour, CloseLocal: 18 * time.Hour},
			5: {OpenLocal: 9 * time.Hour, CloseLocal: 18 * time.Hour},
			6: {OpenLocal: 10 * time.Hour, CloseLocal: 17 * time.Hour}, // Sat 10-5
		},
		HolidayBlackout: []HolidayMatcher{
			{Kind: "fixed", Value: "2026-12-25"}, // Christmas
		},
		Comment: "R.I. Gen. Laws 5-61-2; most restrictive state (9-6 M-F, 10-5 Sat, Sun blackout)",
	},
	"TX": {
		Code: "TX",
		PerDow: [7]Window{
			0: {OpenLocal: 12 * time.Hour, CloseLocal: 21 * time.Hour}, // Sun noon start
			1: {OpenLocal: 9 * time.Hour, CloseLocal: 21 * time.Hour},
			2: {OpenLocal: 9 * time.Hour, CloseLocal: 21 * time.Hour},
			3: {OpenLocal: 9 * time.Hour, CloseLocal: 21 * time.Hour},
			4: {OpenLocal: 9 * time.Hour, CloseLocal: 21 * time.Hour},
			5: {OpenLocal: 9 * time.Hour, CloseLocal: 21 * time.Hour},
			6: {OpenLocal: 9 * time.Hour, CloseLocal: 21 * time.Hour},
		},
		Comment: "Tex. Bus. & Com. Code 301.051 (SB 140); 9am M-Sat, noon Sun",
	},
	"UT": {
		Code: "UT",
		PerDow: [7]Window{
			0: {OpenLocal: 25 * time.Hour, CloseLocal: 0}, // Sunday blackout
			1: {OpenLocal: 8 * time.Hour, CloseLocal: 21 * time.Hour},
			2: {OpenLocal: 8 * time.Hour, CloseLocal: 21 * time.Hour},
			3: {OpenLocal: 8 * time.Hour, CloseLocal: 21 * time.Hour},
			4: {OpenLocal: 8 * time.Hour, CloseLocal: 21 * time.Hour},
			5: {OpenLocal: 8 * time.Hour, CloseLocal: 21 * time.Hour},
			6: {OpenLocal: 8 * time.Hour, CloseLocal: 21 * time.Hour},
		},
		HolidayBlackout: []HolidayMatcher{
			{Kind: "fixed", Value: "2026-12-25"}, // Christmas
		},
		Comment: "Utah Code Ann. 13-25a-103; Sunday blackout",
	},
	"WA": {
		Code: "WA",
		PerDow: [7]Window{
			0: {OpenLocal: 8 * time.Hour, CloseLocal: 20 * time.Hour},
			1: {OpenLocal: 8 * time.Hour, CloseLocal: 20 * time.Hour},
			2: {OpenLocal: 8 * time.Hour, CloseLocal: 20 * time.Hour},
			3: {OpenLocal: 8 * time.Hour, CloseLocal: 20 * time.Hour},
			4: {OpenLocal: 8 * time.Hour, CloseLocal: 20 * time.Hour},
			5: {OpenLocal: 8 * time.Hour, CloseLocal: 20 * time.Hour},
			6: {OpenLocal: 8 * time.Hour, CloseLocal: 20 * time.Hour},
		},
		Comment: "RCW 80.36.390; 8pm cutoff; no B2B exemption",
	},
	"WY": {
		Code: "WY",
		PerDow: [7]Window{
			0: {OpenLocal: 8 * time.Hour, CloseLocal: 20 * time.Hour},
			1: {OpenLocal: 8 * time.Hour, CloseLocal: 20 * time.Hour},
			2: {OpenLocal: 8 * time.Hour, CloseLocal: 20 * time.Hour},
			3: {OpenLocal: 8 * time.Hour, CloseLocal: 20 * time.Hour},
			4: {OpenLocal: 8 * time.Hour, CloseLocal: 20 * time.Hour},
			5: {OpenLocal: 8 * time.Hour, CloseLocal: 20 * time.Hour},
			6: {OpenLocal: 8 * time.Hour, CloseLocal: 20 * time.Hour},
		},
		Comment: "Wyo. Stat. 40-12-302; 8pm cutoff",
	},
}
