// I03 — VoicemailRenderer
// Generates FreeSWITCH dialplan extensions for voicemail boxes.
//
// Extension naming (FROZEN — I02 transfers to these):
//   voicemail_{box_id}  in  freeswitch/conf/dialplan/default/75_voicemail_{box_id}.xml
//
// Caller flow:
//   1. answer
//   2. play greeting (custom or system default)
//   3. play beep tone
//   4. record to local path
//   5. POST webhook to /api/internal/voicemail/recorded
//   6. hangup

import fs from "node:fs/promises";
import path from "node:path";
import pino from "pino";
import type { PrismaClient } from "@prisma/client";

const logger = pino({
  level: process.env.LOG_LEVEL ?? "info",
  base: { service: "i03-vm-renderer" },
});

// ─── Constants ────────────────────────────────────────────────────────────────

const FS_DIALPLAN_DIR =
  process.env.FS_DIALPLAN_DIR ??
  "/root/vici2/.claude/worktrees/agent-ac862c3e29618412f/freeswitch/conf/dialplan/default";

const FS_SOUNDS_DIR =
  process.env.FS_SOUNDS_DIR ?? "/var/lib/freeswitch/sounds";

const FS_RECORDINGS_DIR =
  process.env.FS_RECORDINGS_DIR ?? "/var/lib/freeswitch/recordings";

const API_URL = process.env.API_URL ?? "http://api:3000";

const SYSTEM_GREETING_PATH = `${FS_SOUNDS_DIR}/ivr/sys/sys_voicemail_default.wav`;

// ─── ESL interface (minimal) ──────────────────────────────────────────────────
interface EslClient {
  bgapi(cmd: string): Promise<void>;
}

let _eslClient: EslClient | null = null;

function getEslClient(): EslClient {
  if (_eslClient) return _eslClient;
  // Phase 1: no-op ESL client; bgapi reloadxml called via shell in dev.
  // T01 integration wires a real ESL client on boot; set via setEslClient().
  return {
    async bgapi(cmd: string): Promise<void> {
      logger.info({ cmd }, "vm-renderer: bgapi (stub)");
    },
  };
}

export function setEslClient(client: EslClient): void {
  _eslClient = client;
}

// ─── Renderer ─────────────────────────────────────────────────────────────────

export class VoicemailRenderer {
  constructor(private readonly prisma: PrismaClient) {}

  /**
   * Render dialplan XML for a single voicemail box.
   * Called on create / update / activate / deactivate.
   */
  async render(boxId: bigint): Promise<void> {
    const box = await this.prisma.voicemailBox.findUnique({
      where: { id: boxId },
    });

    if (!box) {
      throw new Error(`VoicemailBox ${boxId} not found`);
    }

    // Read env var at call time so tests can override it.
    const dialplanDir =
      process.env.FS_DIALPLAN_DIR ??
      "/root/vici2/.claude/worktrees/agent-ac862c3e29618412f/freeswitch/conf/dialplan/default";

    const filePath = path.join(
      dialplanDir,
      `75_voicemail_${boxId}.xml`,
    );

    if (!box.active) {
      // Remove XML and reload; inactive box should not accept calls
      try {
        await fs.unlink(filePath);
        logger.info({ boxId: String(boxId) }, "vm-renderer: removed inactive box XML");
      } catch {
        // File may not exist; ignore
      }
      await this.reloadXml();
      return;
    }

    const greetingPath = box.greetingUri ?? SYSTEM_GREETING_PATH;

    // Recording path template — expanded at call time by FS channel vars
    const recordPath = `${FS_RECORDINGS_DIR}/\${vici2_tenant_id}/voicemail/%Y/%m/%d/vm_${boxId}_\${uuid}.wav`;

    const xml = this.generateXml({
      boxId: String(boxId),
      tenantId: String(box.tenantId),
      greetingPath,
      recordPath,
      maxDurationSec: box.maxDurationSec,
    });

    await this.writeXml(filePath, xml);
    await this.reloadXml();
    logger.info({ boxId: String(boxId), filePath }, "vm-renderer: rendered");
  }

  /** Remove all dialplan XML for a box (on hard delete). */
  async remove(boxId: bigint): Promise<void> {
    const dialplanDir =
      process.env.FS_DIALPLAN_DIR ??
      "/root/vici2/.claude/worktrees/agent-ac862c3e29618412f/freeswitch/conf/dialplan/default";
    const filePath = path.join(dialplanDir, `75_voicemail_${boxId}.xml`);
    try {
      await fs.unlink(filePath);
    } catch {
      // OK if file doesn't exist
    }
    await this.reloadXml();
  }

  // ─── Private ───────────────────────────────────────────────────────────────

  private generateXml(params: {
    boxId: string;
    tenantId: string;
    greetingPath: string;
    recordPath: string;
    maxDurationSec: number;
  }): string {
    const { boxId, tenantId, greetingPath, recordPath, maxDurationSec } = params;
    return `<?xml version="1.0" encoding="UTF-8"?>
<!--
  Auto-generated by I03 VoicemailRenderer — DO NOT EDIT.
  Voicemail box: ${boxId} | Tenant: ${tenantId}
  I03 PLAN §2.1: extension name = voicemail_${boxId}
  I02 PLAN §4.3: IVR terminal_voicemail transfers to this extension.
-->
<include>
  <extension name="voicemail_${boxId}" continue="false">
    <condition field="destination_number" expression="^voicemail_${boxId}$">
      <!-- Tag call role and mailbox -->
      <action application="set" data="vici2_role=voicemail"/>
      <action application="set" data="vici2_vm_box_id=${boxId}"/>
      <action application="set" data="vici2_tenant_id=${tenantId}"/>
      <!-- Answer the call -->
      <action application="answer"/>
      <!-- Play greeting (custom or system default) -->
      <action application="playback" data="${greetingPath}"/>
      <!-- Beep tone: 500ms at 440 Hz -->
      <action application="playback" data="tone_stream://%(500,0,440)"/>
      <!-- Record caller's message -->
      <action application="record" data="${recordPath} ${maxDurationSec} 200 3"/>
      <!-- Notify API (fire-and-forget via bgapi curl) -->
      <action application="set" data="vm_notify_url=${API_URL}/api/internal/voicemail/recorded"/>
      <action application="set" data="vm_post_body=box_id=${boxId}&amp;call_uuid=\${uuid}&amp;tenant_id=${tenantId}&amp;caller_number=\${caller_id_number}&amp;duration_sec=\${record_seconds}&amp;file_path=\${record_name}"/>
      <action application="curl" data="\${vm_notify_url} post \${vm_post_body}"/>
      <!-- Hang up gracefully -->
      <action application="hangup" data="NORMAL_CLEARING"/>
    </condition>
  </extension>
</include>
`;
  }

  private async writeXml(filePath: string, content: string): Promise<void> {
    const tmpPath = `${filePath}.tmp`;
    await fs.writeFile(tmpPath, content, "utf8");
    await fs.rename(tmpPath, filePath);
  }

  private async reloadXml(): Promise<void> {
    const esl = getEslClient();
    await esl.bgapi("reloadxml");
  }
}

// ─── Singleton ────────────────────────────────────────────────────────────────

let _renderer: VoicemailRenderer | null = null;

export function getVoicemailRenderer(prisma: PrismaClient): VoicemailRenderer {
  if (!_renderer) {
    _renderer = new VoicemailRenderer(prisma);
  }
  return _renderer;
}
