#!/usr/bin/env python3
"""
infra/kamailio/scripts/dispatcher-list-renderer.py
X02 — Sync the Kamailio dispatcher table from the vici2 FS registry.

Reads the vici2.fs_instances table and writes matching rows to the Kamailio
dispatcher table (sets 1 and 2). Triggers a live reload via kamcmd so changes
take effect without a Kamailio restart.

Usage:
  # Full sync from vici2 DB (replaces sets 1 and 2)
  python3 dispatcher-list-renderer.py --action=sync

  # Add a new FS instance to sets 1 and 2
  python3 dispatcher-list-renderer.py --action=add --fs-ip=10.0.1.12 --sets=1,2

  # Gracefully drain: new calls skip this FS (in-flight calls complete)
  python3 dispatcher-list-renderer.py --action=drain --fs-ip=10.0.1.11

  # Remove an FS from all sets (hard remove, use drain first)
  python3 dispatcher-list-renderer.py --action=remove --fs-ip=10.0.1.11

Environment variables:
  KAMAILIO_DB_HOST, KAMAILIO_DB_PORT, KAMAILIO_DB_USER, KAMAILIO_DB_PASS,
  KAMAILIO_DB_NAME  — Kamailio database connection
  DATABASE_HOST, DATABASE_PORT, DATABASE_USER, DATABASE_PASS, DATABASE_NAME
    — vici2 application database (source of FS registry)
  DISPATCHER_LIST_FILE — path to dispatcher.list fallback file (optional)
"""

import argparse
import subprocess
import sys
import os
import pymysql
import pymysql.cursors

# ---------------------------------------------------------------------------
# Connection configuration from environment (no hardcoded credentials)
# ---------------------------------------------------------------------------

KAMAILIO_DB = {
    'host':     os.environ.get('KAMAILIO_DB_HOST', '127.0.0.1'),
    'port':     int(os.environ.get('KAMAILIO_DB_PORT', '3306')),
    'user':     os.environ.get('KAMAILIO_DB_USER', 'kamailio'),
    'password': os.environ.get('KAMAILIO_DB_PASS', ''),
    'database': os.environ.get('KAMAILIO_DB_NAME', 'kamailio'),
    'cursorclass': pymysql.cursors.DictCursor,
    'connect_timeout': 5,
}

VICI2_DB = {
    'host':     os.environ.get('DATABASE_HOST', '127.0.0.1'),
    'port':     int(os.environ.get('DATABASE_PORT', '3306')),
    'user':     os.environ.get('DATABASE_USER', 'vici2'),
    'password': os.environ.get('DATABASE_PASS', ''),
    'database': os.environ.get('DATABASE_NAME', 'vici2'),
    'cursorclass': pymysql.cursors.DictCursor,
    'connect_timeout': 5,
}

DISPATCHER_LIST_FILE = os.environ.get(
    'DISPATCHER_LIST_FILE', '/etc/kamailio/dispatcher.list'
)

# Dispatcher flag values (bitmask)
DS_FLAG_ACTIVE   = 0
DS_FLAG_INACTIVE = 1  # DS_INACTIVE_DST — skipped for new calls

# Default SIP port for FS
FS_SIP_PORT_DEFAULT = 5060

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def kamcmd_reload(cmd: str = 'dispatcher.reload') -> bool:
    """Trigger a Kamailio management command via kamcmd."""
    try:
        result = subprocess.run(
            ['kamcmd', cmd],
            capture_output=True, text=True, timeout=10
        )
        if result.returncode != 0:
            print(f"WARNING: kamcmd {cmd} failed: {result.stderr.strip()}",
                  file=sys.stderr)
            return False
        print(f"kamcmd {cmd}: OK")
        return True
    except FileNotFoundError:
        print("WARNING: kamcmd not found — skipping live reload", file=sys.stderr)
        return False
    except subprocess.TimeoutExpired:
        print(f"WARNING: kamcmd {cmd} timed out", file=sys.stderr)
        return False


def write_fallback_file(kam_conn: pymysql.Connection) -> None:
    """Write current dispatcher table to the flat-file fallback."""
    rows = []
    with kam_conn.cursor() as cur:
        cur.execute(
            "SELECT setid, flags, priority, attrs, destination "
            "FROM dispatcher ORDER BY setid, id"
        )
        for row in cur.fetchall():
            weight_str = row['attrs'] if row['attrs'] else 'weight=1'
            rows.append(
                f"{row['setid']} {row['flags']} {row['priority']} "
                f"{weight_str} {row['destination']}"
            )
    content = (
        "# dispatcher.list — auto-generated by dispatcher-list-renderer.py\n"
        "# Do not edit manually; re-run --action=sync to regenerate.\n"
        + "\n".join(rows) + "\n"
    )
    try:
        with open(DISPATCHER_LIST_FILE, 'w') as f:
            f.write(content)
        print(f"Wrote fallback file: {DISPATCHER_LIST_FILE} ({len(rows)} entries)")
    except OSError as e:
        print(f"WARNING: could not write {DISPATCHER_LIST_FILE}: {e}", file=sys.stderr)


def get_vici2_fs_instances(vici2_conn: pymysql.Connection) -> list:
    """Read active + draining FS instances from the vici2 fs_instances table."""
    with vici2_conn.cursor() as cur:
        cur.execute("""
            SELECT ip_address, sip_port, weight, status
            FROM fs_instances
            WHERE status IN ('active', 'draining')
            ORDER BY id
        """)
        return cur.fetchall()


def get_vici2_fs_nodes(vici2_conn: pymysql.Connection) -> list:
    """Read FS nodes from the vici2 fs_nodes table (X03).

    Returns rows with host, weight, name, status for set 20 population.
    Only ACTIVE and DRAINING nodes are returned; OFFLINE/UNHEALTHY are excluded.
    """
    with vici2_conn.cursor() as cur:
        cur.execute("""
            SELECT id, host, weight, name, status
            FROM fs_nodes
            WHERE status IN ('ACTIVE', 'DRAINING')
            ORDER BY id
        """)
        return cur.fetchall()


def sync_set_20(kam_conn: pymysql.Connection, fs_nodes: list) -> None:
    """Sync active FS nodes to Kamailio dispatcher set 20 (X03 campaign affinity).

    Set 20 uses algorithm 8 (hash by PV / AVP) for affinity routing.
    DRAINING nodes are inserted with DS_FLAG_INACTIVE so new calls skip them
    while OPTIONS probing is still active (Kamailio marks them manually anyway).
    """
    with kam_conn.cursor() as cur:
        cur.execute("DELETE FROM dispatcher WHERE setid = 20")
        count = 0
        for node in fs_nodes:
            host   = node['host']
            weight = node.get('weight') or 100
            name   = node.get('name') or f"fs-{node['id']}"
            status = node.get('status', 'ACTIVE')
            dst    = f"sip:{host}:{FS_SIP_PORT_DEFAULT}"
            flags  = DS_FLAG_INACTIVE if status == 'DRAINING' else DS_FLAG_ACTIVE
            cur.execute(
                "INSERT INTO dispatcher "
                "(setid, destination, flags, priority, attrs, description) "
                "VALUES (20, %s, %s, %s, %s, %s)",
                (dst, flags, weight, f"weight={weight}", name)
            )
            count += 1
    kam_conn.commit()
    print(f"Set 20 synced: {count} FS node(s) from fs_nodes table.")

# ---------------------------------------------------------------------------
# Actions
# ---------------------------------------------------------------------------

def action_sync(args: argparse.Namespace) -> int:
    """Full sync: replace dispatcher sets 1, 2, and 20 from vici2 tables.

    Sets 1 + 2 are sourced from fs_instances (legacy/static registry).
    Set 20 is sourced from fs_nodes (X03 dynamic affinity nodes).
    """
    vici2_conn = pymysql.connect(**VICI2_DB)
    instances  = get_vici2_fs_instances(vici2_conn)
    fs_nodes   = get_vici2_fs_nodes(vici2_conn)
    vici2_conn.close()

    if not instances:
        print("WARNING: no active FS instances in vici2 DB — leaving sets 1/2 unchanged",
              file=sys.stderr)
        # Don't return 1 — we still want to sync set 20.

    kam_conn = pymysql.connect(**KAMAILIO_DB)
    try:
        with kam_conn.cursor() as cur:
            cur.execute("DELETE FROM dispatcher WHERE setid IN (1, 2)")
            count = 0
            for fs in instances:
                ip     = fs['ip_address']
                port   = fs.get('sip_port') or FS_SIP_PORT_DEFAULT
                weight = fs.get('weight') or 1
                status = fs.get('status', 'active')
                dst    = f"sip:{ip}:{port}"
                flags  = DS_FLAG_INACTIVE if status == 'draining' else DS_FLAG_ACTIVE

                for setid in [1, 2]:
                    cur.execute(
                        "INSERT INTO dispatcher "
                        "(setid, destination, flags, priority, attrs, description) "
                        "VALUES (%s, %s, %s, %s, %s, %s)",
                        (setid, dst, flags, 0, f'weight={weight}', f'fs-{ip}')
                    )
                    count += 1

        kam_conn.commit()
        print(f"Synced {len(instances)} FS instances ({count} rows) to sets 1+2.")

        # X03: sync set 20 from fs_nodes table.
        if fs_nodes:
            sync_set_20(kam_conn, fs_nodes)
        else:
            print("INFO: no fs_nodes rows — set 20 cleared (empty).")
            with kam_conn.cursor() as cur:
                cur.execute("DELETE FROM dispatcher WHERE setid = 20")
            kam_conn.commit()

        write_fallback_file(kam_conn)
    finally:
        kam_conn.close()

    kamcmd_reload()
    return 0


def action_add(args: argparse.Namespace) -> int:
    """Add a single FS instance to the specified sets."""
    if not args.fs_ip:
        print("ERROR: --fs-ip is required for --action=add", file=sys.stderr)
        return 1

    sets   = [int(s) for s in args.sets.split(',')]
    port   = int(args.fs_port or FS_SIP_PORT_DEFAULT)
    weight = int(args.weight or 1)
    dst    = f"sip:{args.fs_ip}:{port}"

    kam_conn = pymysql.connect(**KAMAILIO_DB)
    try:
        with kam_conn.cursor() as cur:
            for setid in sets:
                # Upsert: remove existing entry for this IP+set, then insert
                cur.execute(
                    "DELETE FROM dispatcher WHERE setid=%s AND destination LIKE %s",
                    (setid, f'sip:{args.fs_ip}:%')
                )
                cur.execute(
                    "INSERT INTO dispatcher "
                    "(setid, destination, flags, priority, attrs, description) "
                    "VALUES (%s, %s, %s, %s, %s, %s)",
                    (setid, dst, DS_FLAG_ACTIVE, 0, f'weight={weight}', f'fs-{args.fs_ip}')
                )
                print(f"Added {dst} to set {setid}")
        kam_conn.commit()
        write_fallback_file(kam_conn)
    finally:
        kam_conn.close()

    kamcmd_reload()
    return 0


def action_drain(args: argparse.Namespace) -> int:
    """Drain an FS: mark as inactive in dispatcher (new calls skip it)."""
    if not args.fs_ip:
        print("ERROR: --fs-ip is required for --action=drain", file=sys.stderr)
        return 1

    kam_conn = pymysql.connect(**KAMAILIO_DB)
    try:
        with kam_conn.cursor() as cur:
            rows = cur.execute(
                "UPDATE dispatcher SET flags=%s WHERE destination LIKE %s",
                (DS_FLAG_INACTIVE, f'sip:{args.fs_ip}:%')
            )
        kam_conn.commit()
        print(f"Drained {args.fs_ip}: {rows} dispatcher rows set to inactive")
        write_fallback_file(kam_conn)
    finally:
        kam_conn.close()

    kamcmd_reload()
    # Also update the live state via kamcmd (immediate effect without DS reload lag)
    kamcmd_reload(f'dispatcher.set_state ip sip:{args.fs_ip}:5060 1')
    return 0


def action_remove(args: argparse.Namespace) -> int:
    """Hard-remove an FS from all dispatcher sets."""
    if not args.fs_ip:
        print("ERROR: --fs-ip is required for --action=remove", file=sys.stderr)
        return 1

    kam_conn = pymysql.connect(**KAMAILIO_DB)
    try:
        with kam_conn.cursor() as cur:
            rows = cur.execute(
                "DELETE FROM dispatcher WHERE destination LIKE %s",
                (f'sip:{args.fs_ip}:%',)
            )
        kam_conn.commit()
        print(f"Removed {args.fs_ip}: {rows} dispatcher rows deleted")
        write_fallback_file(kam_conn)
    finally:
        kam_conn.close()

    kamcmd_reload()
    return 0

# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

ACTIONS = {
    'sync':   action_sync,
    'add':    action_add,
    'drain':  action_drain,
    'remove': action_remove,
}


def main() -> int:
    parser = argparse.ArgumentParser(
        description='Sync Kamailio dispatcher table from vici2 FS registry'
    )
    parser.add_argument(
        '--action', required=True, choices=list(ACTIONS.keys()),
        help='Operation to perform'
    )
    parser.add_argument('--fs-ip',   help='FS IP address (for add/drain/remove)')
    parser.add_argument('--fs-port', help='FS SIP port (default 5060)', default=None)
    parser.add_argument('--sets',    help='Comma-separated set IDs (default 1,2)',
                        default='1,2')
    parser.add_argument('--weight',  help='Weight for new entry (default 1)', default=None)
    args = parser.parse_args()

    return ACTIONS[args.action](args)


if __name__ == '__main__':
    sys.exit(main())
