// Code generated by tcpa-rulesgen; DO NOT EDIT.
// Source: db/seeds/state_rules.csv
// Generated: 2026-05-13
// Expanded 5-year holiday calendar (2026–2030) for state holiday blackout checks.

/**
 * STATE_HOLIDAYS maps state codes to sets of "YYYY-MM-DD" strings.
 * Includes fixed dates, computed Easter offsets, and named holidays (Mardi Gras).
 */
export const STATE_HOLIDAYS: Readonly<Record<string, ReadonlySet<string>>> = {
  AL: new Set([
    // New Year's Day
    '2026-01-01', '2027-01-01', '2028-01-01', '2029-01-01', '2030-01-01',
    // Christmas
    '2026-12-25', '2027-12-25', '2028-12-25', '2029-12-25', '2030-12-25',
  ]),
  LA: new Set([
    // Mardi Gras (Easter - 47): 2026-02-17, 2027-03-09, 2028-02-29, 2029-02-13, 2030-03-05
    '2026-02-17', '2027-03-09', '2028-02-29', '2029-02-13', '2030-03-05',
    // Good Friday (Easter - 2): 2026-04-03, 2027-03-26, 2028-04-14, 2029-03-30, 2030-04-19
    '2026-04-03', '2027-03-26', '2028-04-14', '2029-03-30', '2030-04-19',
  ]),
  RI: new Set([
    '2026-12-25', '2027-12-25', '2028-12-25', '2029-12-25', '2030-12-25',
  ]),
  UT: new Set([
    '2026-12-25', '2027-12-25', '2028-12-25', '2029-12-25', '2030-12-25',
  ]),
};
