// Code generated by tcpa-rulesgen from db/seeds/state_rules.csv; DO NOT EDIT.
// Source: db/seeds/state_rules.csv
// Generated: 2026-05-13

import type { Window } from './types.js';

/** Seconds since midnight helpers */
const H = (h: number): number => h * 3600;

/** Window that represents a full-day blackout (open > close). */
const BLACKOUT: Window = { openLocal: 25 * 3600, closeLocal: 0 };

export interface StateRule {
  code: string;
  /** Index 0=Sun … 6=Sat. Undefined or zero = use federal floor. */
  perDow: [Window?, Window?, Window?, Window?, Window?, Window?, Window?];
  holidayBlackout?: Array<{ kind: 'fixed' | 'easter_offset' | 'named'; value: string }>;
  /** Narrower window for autodialers (M-F only for ME). */
  autoDialerOnly?: Window;
  /** Bitmask of dow where autodialers are fully barred (bit 0=Sun, bit 6=Sat). */
  autoDialerBlackoutDows?: number;
  comment?: string;
}

/** Federal floor: 08:00–21:00 every day. */
export const FED_FLOOR: Window = { openLocal: H(8), closeLocal: H(21) };

export const STATE_RULES: Readonly<Record<string, StateRule>> = {
  AL: {
    code: 'AL',
    perDow: [
      BLACKOUT,                                           // Sun
      { openLocal: H(8), closeLocal: H(20) },            // Mon
      { openLocal: H(8), closeLocal: H(20) },            // Tue
      { openLocal: H(8), closeLocal: H(20) },            // Wed
      { openLocal: H(8), closeLocal: H(20) },            // Thu
      { openLocal: H(8), closeLocal: H(20) },            // Fri
      { openLocal: H(8), closeLocal: H(20) },            // Sat
    ],
    holidayBlackout: [
      { kind: 'fixed', value: '2026-01-01' },
      { kind: 'fixed', value: '2026-12-25' },
    ],
    comment: 'Ala. Admin. Code 770-X-5-.17',
  },
  CT: {
    code: 'CT',
    perDow: Array(7).fill({ openLocal: H(9), closeLocal: H(20) }) as StateRule['perDow'],
    comment: 'Conn. Gen. Stat. 42-288a(c); 9am start + 8pm cutoff',
  },
  FL: {
    code: 'FL',
    perDow: Array(7).fill({ openLocal: H(8), closeLocal: H(20) }) as StateRule['perDow'],
    comment: 'Fla. Stat. 501.616 (FTSA); 8pm cutoff',
  },
  KY: {
    code: 'KY',
    perDow: Array(7).fill({ openLocal: H(10), closeLocal: H(21) }) as StateRule['perDow'],
    comment: 'KRS 367.46955; 10am start',
  },
  LA: {
    code: 'LA',
    perDow: [
      BLACKOUT,                                           // Sun
      { openLocal: H(8), closeLocal: H(20) },            // Mon
      { openLocal: H(8), closeLocal: H(20) },            // Tue
      { openLocal: H(8), closeLocal: H(20) },            // Wed
      { openLocal: H(8), closeLocal: H(20) },            // Thu
      { openLocal: H(8), closeLocal: H(20) },            // Fri
      { openLocal: H(8), closeLocal: H(20) },            // Sat
    ],
    holidayBlackout: [
      { kind: 'named', value: 'MARDI_GRAS' },
      { kind: 'easter_offset', value: '-2' },
    ],
    comment: 'La. R.S. 45:844.31; 8pm M-Sat; Sunday blackout; Mardi Gras + Good Friday',
  },
  MD: {
    code: 'MD',
    perDow: Array(7).fill({ openLocal: H(8), closeLocal: H(20) }) as StateRule['perDow'],
    comment: 'Md. Com. Law 14-3201; 8pm cutoff',
  },
  MA: {
    code: 'MA',
    perDow: Array(7).fill({ openLocal: H(8), closeLocal: H(20) }) as StateRule['perDow'],
    comment: 'MGL Ch.159C 3; 8pm cutoff',
  },
  ME: {
    code: 'ME',
    perDow: Array(7).fill({ openLocal: H(8), closeLocal: H(21) }) as StateRule['perDow'],
    autoDialerOnly: { openLocal: H(9), closeLocal: H(17) },
    autoDialerBlackoutDows: 0x41, // bit0=Sun, bit6=Sat
    comment: '10 M.R.S. 1498; autodialer M-F 9-5 only; Sat/Sun blackout',
  },
  MI: {
    code: 'MI',
    perDow: Array(7).fill({ openLocal: H(9), closeLocal: H(21) }) as StateRule['perDow'],
    comment: 'MCL 750.540e(f); 9am start',
  },
  MN: {
    code: 'MN',
    perDow: Array(7).fill({ openLocal: H(9), closeLocal: H(21) }) as StateRule['perDow'],
    comment: 'Minn. Stat. 325E.30; 9am start',
  },
  MS: {
    code: 'MS',
    perDow: [
      BLACKOUT,                                           // Sun
      { openLocal: H(8), closeLocal: H(20) },            // Mon
      { openLocal: H(8), closeLocal: H(20) },            // Tue
      { openLocal: H(8), closeLocal: H(20) },            // Wed
      { openLocal: H(8), closeLocal: H(20) },            // Thu
      { openLocal: H(8), closeLocal: H(20) },            // Fri
      { openLocal: H(8), closeLocal: H(20) },            // Sat
    ],
    comment: 'Miss. Code Ann. 77-3-723; 8pm M-Sat; Sunday blackout',
  },
  OK: {
    code: 'OK',
    perDow: Array(7).fill({ openLocal: H(8), closeLocal: H(20) }) as StateRule['perDow'],
    comment: '15 OS 775C.4 (OTSA); 8pm cutoff',
  },
  PA: {
    code: 'PA',
    perDow: [
      { openLocal: H(12), closeLocal: H(21) },           // Sun noon start
      { openLocal: H(8), closeLocal: H(21) },            // Mon
      { openLocal: H(8), closeLocal: H(21) },            // Tue
      { openLocal: H(8), closeLocal: H(21) },            // Wed
      { openLocal: H(8), closeLocal: H(21) },            // Thu
      { openLocal: H(8), closeLocal: H(21) },            // Fri
      { openLocal: H(8), closeLocal: H(21) },            // Sat
    ],
    comment: '73 P.S. 2245.4; Sunday noon start',
  },
  RI: {
    code: 'RI',
    perDow: [
      BLACKOUT,                                           // Sun
      { openLocal: H(9), closeLocal: H(18) },            // Mon
      { openLocal: H(9), closeLocal: H(18) },            // Tue
      { openLocal: H(9), closeLocal: H(18) },            // Wed
      { openLocal: H(9), closeLocal: H(18) },            // Thu
      { openLocal: H(9), closeLocal: H(18) },            // Fri
      { openLocal: H(10), closeLocal: H(17) },           // Sat 10-5
    ],
    holidayBlackout: [{ kind: 'fixed', value: '2026-12-25' }],
    comment: 'R.I. Gen. Laws 5-61-2; most restrictive state',
  },
  TX: {
    code: 'TX',
    perDow: [
      { openLocal: H(12), closeLocal: H(21) },           // Sun noon
      { openLocal: H(9), closeLocal: H(21) },            // Mon
      { openLocal: H(9), closeLocal: H(21) },            // Tue
      { openLocal: H(9), closeLocal: H(21) },            // Wed
      { openLocal: H(9), closeLocal: H(21) },            // Thu
      { openLocal: H(9), closeLocal: H(21) },            // Fri
      { openLocal: H(9), closeLocal: H(21) },            // Sat
    ],
    comment: 'Tex. Bus. & Com. Code 301.051 (SB 140)',
  },
  UT: {
    code: 'UT',
    perDow: [
      BLACKOUT,                                           // Sun
      { openLocal: H(8), closeLocal: H(21) },            // Mon
      { openLocal: H(8), closeLocal: H(21) },            // Tue
      { openLocal: H(8), closeLocal: H(21) },            // Wed
      { openLocal: H(8), closeLocal: H(21) },            // Thu
      { openLocal: H(8), closeLocal: H(21) },            // Fri
      { openLocal: H(8), closeLocal: H(21) },            // Sat
    ],
    holidayBlackout: [{ kind: 'fixed', value: '2026-12-25' }],
    comment: 'Utah Code Ann. 13-25a-103; Sunday blackout',
  },
  WA: {
    code: 'WA',
    perDow: Array(7).fill({ openLocal: H(8), closeLocal: H(20) }) as StateRule['perDow'],
    comment: 'RCW 80.36.390; 8pm cutoff; no B2B exemption',
  },
  WY: {
    code: 'WY',
    perDow: Array(7).fill({ openLocal: H(8), closeLocal: H(20) }) as StateRule['perDow'],
    comment: 'Wyo. Stat. 40-12-302; 8pm cutoff',
  },
} as const;
