// Code generated by consent-rulesgen from db/seeds/consent_rules.csv; DO NOT EDIT.
// Source: db/seeds/consent_rules.csv
// Generated: 2026-05-13

package consent

// stateRules maps 2-letter US state codes to their recording-consent rules.
// States absent from this map default to ModeAllow (1-party federal floor, 18 USC §2511(2)(d)).
var stateRules = map[string]ConsentRule{
	"CA": {State: "CA", MinimumMode: ModePromptMessage, BeepAccepted: false, B2BExempt: false, Citation: "Cal. Penal Code §§632 632.7"}, // CIPA; $5K/call §637.2
	"CT": {State: "CT", MinimumMode: ModePromptMessage, BeepAccepted: false, B2BExempt: false, Citation: "Conn. Gen. Stat. §52-570d"},   // Civil-safety posture
	"DE": {State: "DE", MinimumMode: ModePromptMessage, BeepAccepted: false, B2BExempt: false, Citation: "11 Del.C. §1335"},
	"FL": {State: "FL", MinimumMode: ModePromptMessage, BeepAccepted: false, B2BExempt: false, Citation: "Fla. Stat. §934.03"},            // Felony violation
	"IL": {State: "IL", MinimumMode: ModePromptMessage, BeepAccepted: false, B2BExempt: false, Citation: "720 ILCS 5/14-2"},               // Post-2014 intent-to-be-private test
	"MD": {State: "MD", MinimumMode: ModePromptMessage, BeepAccepted: false, B2BExempt: false, Citation: "Md. Cts. & Jud. Proc. §10-402"}, // Felony
	"MA": {State: "MA", MinimumMode: ModePromptMessage, BeepAccepted: false, B2BExempt: false, Citation: "Mass. Gen. Laws ch.272 §99"},    // Secretly test (§99 operative word)
	"MI": {State: "MI", MinimumMode: ModePromptMessage, BeepAccepted: false, B2BExempt: false, Citation: "Mich. Comp. Laws §750.539c"},    // Sullivan v. Gray conservative read
	"MT": {State: "MT", MinimumMode: ModePromptMessage, BeepAccepted: false, B2BExempt: false, Citation: "Mont. Code Ann. §45-8-213"},
	"NH": {State: "NH", MinimumMode: ModePromptMessage, BeepAccepted: false, B2BExempt: false, Citation: "N.H. Rev. Stat. §570-A:2"},  // Strictest tier
	"OR": {State: "OR", MinimumMode: ModePromptMessage, BeepAccepted: false, B2BExempt: false, Citation: "Or. Rev. Stat. §165.540"},   // Phone tech 1-party; UTPA overlay → 2-party posture
	"PA": {State: "PA", MinimumMode: ModePromptMessage, BeepAccepted: false, B2BExempt: true, Citation: "18 Pa.C.S. §§5703-5704"},     // B2B carveout §5704(15); 1-yr retention
	"WA": {State: "WA", MinimumMode: ModePromptMessage, BeepAccepted: false, B2BExempt: false, Citation: "Wash. Rev. Code §9.73.030"}, // Announcement-then-continued-call doctrine
}
