// Package main is the I02 IVR bridge daemon (ivrbridge) — Phase 2 stub.
//
// Phase 2 will implement dynamic per-call ESL control for IVR trees
// with ivrbridge phase flag (ivrs.phase='ivrbridge').
//
// Phase 1: all IVR execution is handled by static FreeSWITCH dialplan XML
// generated by IvrRenderer (api/src/services/ivr/IvrRenderer.ts).
// This binary is intentionally a no-op stub until Phase 2 ships.
package main

import (
	"log/slog"
	"os"
)

func main() {
	log := slog.New(slog.NewJSONHandler(os.Stderr, &slog.HandlerOptions{Level: slog.LevelInfo}))
	log.Info("ivrbridge not yet implemented (Phase 2)", "module", "ivrbridge")
	os.Exit(0)
}
